/*******************************************************************************
 * @file mc_stepper_can_dbc.c
 * @brief Auto-generated CAN message definitions from DBC file.
 *******************************************************************************
 */

/** Includes. *****************************************************************/

#include "mc_stepper_can_dbc.h"

/** Public variables. *********************************************************/

const can_message_t dbc_messages[] = {
    {
        .name = "state",
        .message_id = 32,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 1,
        .signals =
            {
                {
                    .name = "system_state",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "stallguard_event",
        .message_id = 64,
        .id_mask = 0xFFFFFFFF,
        .dlc = 5,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 4,
        .signals =
            {
                {
                    .name = "node_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "sg_result",
                    .start_bit = 8,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 1023.0f,
                },
                {
                    .name = "sgthrs",
                    .start_bit = 24,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "stalled",
                    .start_bit = 32,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 1.0f,
                },
            },
    },
    {
        .name = "absolute_encoder",
        .message_id = 96,
        .id_mask = 0xFFFFFFFF,
        .dlc = 4,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "node_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "raw_position",
                    .start_bit = 8,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 16383.0f,
                },
                {
                    .name = "status",
                    .start_bit = 24,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "command_stepper",
        .message_id = 128,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 7,
        .signals =
            {
                {
                    .name = "node_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "control_mode",
                    .start_bit = 8,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
                {
                    .name = "enable",
                    .start_bit = 11,
                    .bit_length = 1,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 1.0f,
                },
                {
                    .name = "clear_faults",
                    .start_bit = 12,
                    .bit_length = 1,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 1.0f,
                },
                {
                    .name = "reserved0",
                    .start_bit = 13,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
                {
                    .name = "target_position",
                    .start_bit = 16,
                    .bit_length = 32,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = true,
                    .scale = 0.001f,
                    .offset = 0.0f,
                    .min_value = -2147483.648f,
                    .max_value = 2147483.647f,
                },
                {
                    .name = "target_velocity",
                    .start_bit = 48,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = true,
                    .scale = 0.001f,
                    .offset = 0.0f,
                    .min_value = -32.768f,
                    .max_value = 32.767f,
                },
            },
    },
    {
        .name = "controls_diagnostic",
        .message_id = 160,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 4,
        .signals =
            {
                {
                    .name = "position_setpoint",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = true,
                    .scale = 0.001f,
                    .offset = 0.0f,
                    .min_value = -32.768f,
                    .max_value = 32.767f,
                },
                {
                    .name = "position_error",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = true,
                    .scale = 0.0001f,
                    .offset = 0.0f,
                    .min_value = -3.2768f,
                    .max_value = 3.2767f,
                },
                {
                    .name = "velocity_setpoint",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = true,
                    .scale = 0.001f,
                    .offset = 0.0f,
                    .min_value = -32.768f,
                    .max_value = 32.767f,
                },
                {
                    .name = "step_rate_command",
                    .start_bit = 48,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = true,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = -32768.0f,
                    .max_value = 32767.0f,
                },
            },
    },
    {
        .name = "command_stepper_zero",
        .message_id = 192,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 1,
        .signals =
            {
                {
                    .name = "node_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "motion_config_set",
        .message_id = 224,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 4,
        .signals =
            {
                {
                    .name = "node_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "step_size",
                    .start_bit = 8,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 256.0f,
                },
                {
                    .name = "max_acceleration",
                    .start_bit = 24,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 0.1f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 6553.5f,
                },
                {
                    .name = "max_velocity",
                    .start_bit = 40,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 0.001f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65.535f,
                },
            },
    },
    {
        .name = "motion_config_get",
        .message_id = 256,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 1,
        .signals =
            {
                {
                    .name = "node_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "motion_config_response",
        .message_id = 288,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "step_size",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 256.0f,
                },
                {
                    .name = "max_acceleration",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 0.1f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 6553.5f,
                },
                {
                    .name = "max_velocity",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 0.001f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65.535f,
                },
            },
    },
    {
        .name = "current_config_set",
        .message_id = 320,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 5,
        .signals =
            {
                {
                    .name = "node_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "run_current_ma",
                    .start_bit = 8,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 3000.0f,
                },
                {
                    .name = "current_run",
                    .start_bit = 24,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "current_hold",
                    .start_bit = 32,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "current_hold_delay",
                    .start_bit = 40,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 15.0f,
                },
            },
    },
    {
        .name = "current_config_get",
        .message_id = 352,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 1,
        .signals =
            {
                {
                    .name = "node_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "current_config_response",
        .message_id = 384,
        .id_mask = 0xFFFFFFFF,
        .dlc = 5,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 4,
        .signals =
            {
                {
                    .name = "run_current_ma",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 3000.0f,
                },
                {
                    .name = "current_run",
                    .start_bit = 16,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "current_hold",
                    .start_bit = 24,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "current_hold_delay",
                    .start_bit = 32,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 15.0f,
                },
            },
    },
    {
        .name = "controls_config_set",
        .message_id = 416,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 5,
        .signals =
            {
                {
                    .name = "node_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "reserved0",
                    .start_bit = 8,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "k_p",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 0.001f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65.535f,
                },
                {
                    .name = "k_i",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 0.001f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65.535f,
                },
                {
                    .name = "k_d",
                    .start_bit = 48,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 0.001f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65.535f,
                },
            },
    },
    {
        .name = "controls_config_get",
        .message_id = 448,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 1,
        .signals =
            {
                {
                    .name = "node_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "controls_config_response",
        .message_id = 480,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "k_p",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 0.001f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65.535f,
                },
                {
                    .name = "k_i",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 0.001f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65.535f,
                },
                {
                    .name = "k_d",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 0.001f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65.535f,
                },
            },
    },
    {
        .name = "stallguard_set",
        .message_id = 512,
        .id_mask = 0xFFFFFFFF,
        .dlc = 3,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "node_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "enable",
                    .start_bit = 8,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 1.0f,
                },
                {
                    .name = "sgthrs",
                    .start_bit = 16,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "stallguard_get",
        .message_id = 544,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 1,
        .signals =
            {
                {
                    .name = "node_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "stallguard_response",
        .message_id = 576,
        .id_mask = 0xFFFFFFFF,
        .dlc = 5,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 4,
        .signals =
            {
                {
                    .name = "enable",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 1.0f,
                },
                {
                    .name = "sgthrs",
                    .start_bit = 8,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "sg_result",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 1023.0f,
                },
                {
                    .name = "stalled",
                    .start_bit = 32,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 1.0f,
                },
            },
    },
    {
        .name = "datetime_set",
        .message_id = 608,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 7,
        .signals =
            {
                {
                    .name = "year",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 99.0f,
                },
                {
                    .name = "month",
                    .start_bit = 8,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 1.0f,
                    .max_value = 12.0f,
                },
                {
                    .name = "date",
                    .start_bit = 16,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 1.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "weekday",
                    .start_bit = 24,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 1.0f,
                    .max_value = 7.0f,
                },
                {
                    .name = "hours",
                    .start_bit = 32,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 23.0f,
                },
                {
                    .name = "minutes",
                    .start_bit = 40,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 59.0f,
                },
                {
                    .name = "seconds",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 59.0f,
                },
            },
    },
    {
        .name = "datetime_get",
        .message_id = 640,
        .id_mask = 0xFFFFFFFF,
        .dlc = 0,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 0,
        .signals =
            {

            },
    },
    {
        .name = "datetime_response",
        .message_id = 672,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 7,
        .signals =
            {
                {
                    .name = "year",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 99.0f,
                },
                {
                    .name = "month",
                    .start_bit = 8,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 1.0f,
                    .max_value = 12.0f,
                },
                {
                    .name = "date",
                    .start_bit = 16,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 1.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "weekday",
                    .start_bit = 24,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 1.0f,
                    .max_value = 7.0f,
                },
                {
                    .name = "hours",
                    .start_bit = 32,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 23.0f,
                },
                {
                    .name = "minutes",
                    .start_bit = 40,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 59.0f,
                },
                {
                    .name = "seconds",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 59.0f,
                },
            },
    },
    {
        .name = "rgb_led_set",
        .message_id = 704,
        .id_mask = 0xFFFFFFFF,
        .dlc = 3,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "red",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "green",
                    .start_bit = 8,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "blue",
                    .start_bit = 16,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "version_get",
        .message_id = 960,
        .id_mask = 0xFFFFFFFF,
        .dlc = 0,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 0,
        .signals =
            {

            },
    },
    {
        .name = "version_response",
        .message_id = 992,
        .id_mask = 0xFFFFFFFF,
        .dlc = 4,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 4,
        .signals =
            {
                {
                    .name = "version_major",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "version_minor",
                    .start_bit = 8,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "version_patch",
                    .start_bit = 16,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "version_identifier",
                    .start_bit = 24,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
};
